# Generated by Django 4.1.13 on 2024-01-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directs', '0005_alter_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
