# Generated by Django 4.1.13 on 2023-12-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
